### ISSUE TITLE
Error saving entity - collation not legal

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#337]
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue
My entity was incomplete. This caused it to not show up on the GUI:

{
  "info" : {
    "title" : "Claim",
    "version" : "0.0.1",
    "description" : "Overall claim comprising many lines"
  },
  "definitions" : {
    "Claim" : {
      "primaryKey" : "id",
      "required" : [ ],
      "rangeIndex" : [ ],
      "wordLexicon" : [ ],
      "properties" : {
        "sensitiveIndicator" : {
          "datatype" : "boolean",
          "description" : "is this sensitive info"
        },
        "id" : {
          "datatype" : "nonNegativeInteger",
          "description" : "id"
        },

What behavior are you expecting?

New entity on the screen with three properties.

Which Operating System are you using?
Max Os X

Which version of MarkLogic are you using?
ML 9 Ea3

Which version of the Data Hub Framework are you using?
2.0.0-alpha.1

Is this a QuickStart UI bug? If so, which browser are you using?

#### The devil is in the details...
16:16:05.911 [SimpleAsyncTaskExecutor-5] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.marklogic.quickstart.service.DataHubService.installUserModules(com.marklogic.hub.HubConfig,boolean,com.marklogic.quickstart.listeners.DeployUserModulesListener,com.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Local message: write failed: Internal Server Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepoint not legal . See the MarkLogic server error log for further detail.
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:55)
	at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.marklogic.client.FailedRequestException: Local message: write failed: Internal Server Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepoint not legal . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1536)
	at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1189)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:836)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:708)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:652)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:120)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:94)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand.execute(LoadUserModulesCommand.java:94)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:58)
	at com.marklogic.hub.DataHub.installUserModules(DataHub.java:367)
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:134)
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:52)
	... 7 common frames omitted
16:16:05.911 [SimpleAsyncTaskExecutor-4] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.marklogic.quickstart.service.DataHubService.installUserModules(com.marklogic.hub.HubConfig,boolean,com.marklogic.quickstart.listeners.DeployUserModulesListener,com.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Local message: write failed: Internal Server Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepoint not legal . See the MarkLogic server error log for further detail.
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:55)
	at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.marklogic.client.FailedRequestException: Local message: write failed: Internal Server Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepoint not legal . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseyServices.java:1536)
	at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.java:1189)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:836)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:708)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:652)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:120)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDirectory(LoadUserModulesCommand.java:94)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.marklogic.hub.deploy.commands.LoadUserModulesCommand.execute(LoadUserModulesCommand.java:94)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:58)
	at com.marklogic.hub.DataHub.installUserModules(DataHub.java:367)
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:134)
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:52)
	... 7 common frames omitted

**Comment by paxtonhare** [comment]
closing this. hoping it's fixed.
