### ISSUE TITLE
Error on initial run of QuickStart GUI

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#394]
#### The issue

After initial QuickStart install, I get an XML parse error browsing to localhost:8080.

-----
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue May 02 15:44:55 EDT 2017
There was an unexpected error (type=Internal Server Error, status=500).
Exception parsing document: template="index", line 23 - column 72
------

Which Operating System are you using?
Mac OS X

Which version of MarkLogic are you using?
ML 9 nightly 05/02

Which version of the Data Hub Framework are you using?
2.0.0-alpha-2

Is this a QuickStart UI bug? If so, which browser are you using?
No. Error before UI processing. Using Chrome.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

15:44:36.359 [main] INFO  com.marklogic.quickstart.Application - Starting Application on MacPro-2903 with PID 42995 (/Users/df
eldman/ProjectRepos/DataHub-Insurance-AM-Demo/hub/quick-start-2.0.0-alpha.2.war started by dfeldman in /Users/dfeldman/Project
Repos/DataHub-Insurance-AM-Demo/hub)
15:44:36.364 [main] INFO  com.marklogic.quickstart.Application - The following profiles are active: production
15:44:43.811 [main] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: com.marklogic.quickstart.WebSocketConfig$$EnhancerBySp
ringCGLIB$$f347f9d3.configureMessageBroker took 0.004290161s
15:44:44.021 [main] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: com.marklogic.quickstart.AuthConfig$$EnhancerBySpringC
GLIB$$38fd40b2.restConfig took 6.73323E-4s
15:44:44.024 [main] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: com.marklogic.quickstart.AuthConfig$$EnhancerBySpringC
GLIB$$38fd40b2.markLogicAuthenticationManager took 0.008714251s
15:44:44.340 [main] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: com.marklogic.quickstart.AuthConfig$$EnhancerBySpringC
GLIB$$38fd40b2.credentialsProvider took 0.003956065s
15:44:44.388 [main] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: com.marklogic.quickstart.WebSocketConfig$$EnhancerBySp
ringCGLIB$$f347f9d3.registerStompEndpoints took 0.005771066s
15:44:49.518 [main] INFO  com.marklogic.quickstart.Application - Started Application in 13.94 seconds (JVM running
 for 14.52)
15:44:54.841 [http-nio-8080-exec-1] ERROR o.t.templateparser.ErrorHandler - [THYMELEAF][http-nio-8080-exec-1] Fatal error during parsing
org.xml.sax.SAXParseException: The element type "link" must be terminated by the matching end-tag "</link>".
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:209)
        at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:134)
        at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:116)
        at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:278)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
        at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
        at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:190)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
:

**Comment by paxtonhare** [comment]
@damonfeldman I'm closing this. Feel free to re-open if the problem resurfaces.
