### ISSUE TITLE
Entity definition partially written, everything hosed

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/marklogic-data-hub#435]
A London workshop user somehow got into a state where an entity model was only partially written. She was only using the QuickStart UI and not monkeying with the files on the file system.

```json
{
  "info" : {
    "title" : "Order",
    "version" : "0.0.1"
  },
  "definitions" : {
    "Order" : {
      "primaryKey" : "id",
      "required" : [ ],
      "rangeIndex" : [ ],
      "wordLexicon" : [ ],
      "properties" : {
        "id" : {
          "datatype" : "string",
          "collation" : "http://marklogic.com/collation/codepoint"
        },
        "price" : {
          "datatype" : "decimal"
        },
        "products" : {
          "datatype" : "array",
          "items" : {
            "$ref" : "#/definitions/Product"
          }
        },
```
…barf

```
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna
l(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Unknown Source)
13:03:13.177 [http-nio-8080-exec-8] ERROR o.s.w.s.m.SubProtocolWebSocketHandler
- No messages received after 64478 ms. Closing WebSocketServerSockJsSession[id=j
ufysllz].
13:03:18.292 [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] -
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw
exception
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/be
tween Object entries
 at [Source: C:\users\mluser\Desktop\HubHandsOnSession\mlworld\plugins\entities\
Order\Order.entity.json; line: 26, column: 609]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java
:1702)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWS2(UTF8Str
eamJsonParser.java:2922)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWS(UTF8Stre
amJsonParser.java:2892)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UT
F8StreamJsonParser.java:1044)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deseria
lizeObject(JsonNodeDeserializer.java:221)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deseria
lizeObject(JsonNodeDeserializer.java:229)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deseria
lizeObject(JsonNodeDeserializer.java:229)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deseria
lizeObject(JsonNodeDeserializer.java:229)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deseria
lize(JsonNodeDeserializer.java:69)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deseria
lize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
pper.java:3798)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.jav
a:2431)
        at com.marklogic.quickstart.service.EntityManagerService.getEntities(Ent
ityManagerService.java:89)
        at com.marklogic.quickstart.web.EntitiesController.getEntities(EntitiesC
ontroller.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInter
ceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.do
Filter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.session.SessionManagementFilter.doFi
lter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AnonymousAuthenticati
onFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwar
eRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter
.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticatio
nProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.d
oFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterIn
ternal(HeaderWriterFilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFi
lter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManage
rIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.
doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(Fi
lterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChai
nProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(D
elegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(Delegat
ingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(
RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInter
nal(HttpPutFormContentFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna
l(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java
:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig
ht.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract
Protocol.java:861)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas
e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Unknown Source)
13:03:26.414 [SimpleAsyncTaskExecutor-1] ERROR o.s.a.i.SimpleAsyncUncaughtExcept
ionHandler - Unexpected error occurred invoking async method 'public void com.ma
rklogic.quickstart.service.DataHubService.installUserModules(com.marklogic.hub.H
ubConfig,boolean,com.marklogic.quickstart.listeners.DeployUserModulesListener,co
m.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.quickstart.exception.DataHubException: Error in connecting to the
Data Hub API with the following message: Local message: write failed: Internal S
erver Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepoint not legal .
 See the MarkLogic server error log for further detail.
        at com.marklogic.quickstart.service.DataHubService.installUserModules(Da
taHubService.java:84)
        at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGL
IB$$4c244452.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2
04)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation
.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(
ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(
AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.marklogic.client.FailedRequestException: Local message: write fai
led: Internal Server Error. Server Message: SVC-CODEPOINT: (err:FOCH0001) Codepo
int not legal . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.JerseyServices.putPostDocumentImpl(JerseySe
rvices.java:1565)
        at com.marklogic.client.impl.JerseyServices.putDocument(JerseyServices.j
ava:1199)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerIm
pl.java:919)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerIm
pl.java:757)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerIm
pl.java:701)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDi
rectory(LoadUserModulesCommand.java:112)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand$1.preVisitDi
rectory(LoadUserModulesCommand.java:86)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at com.marklogic.hub.deploy.commands.LoadUserModulesCommand.execute(Load
UserModulesCommand.java:86)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractApp
Deployer.java:63)
        at com.marklogic.hub.DataHub.runCommands(DataHub.java:289)
        at com.marklogic.hub.DataHub.installUserModules(DataHub.java:271)
        at com.marklogic.quickstart.service.DataHubService.installUserModules(Da
taHubService.java:189)
        at com.marklogic.quickstart.service.DataHubService.installUserModules(Da
taHubService.java:81)
        ... 7 common frames omitted
```

DataHub 2.0.0-beta1
Windows 7
Java 1.8
Chrome

**Comment by Audarth** [comment]
This just happened to me, I was editing the entity in the UI when after saving some changes I started getting the same errors in the console and the UI stopped functioning properly.

The entity json was incomplete similar to @jmakeig as shown here:

```
{
  "info" : {
    "title" : "Group",
    "version" : "0.0.1"
  },
  "definitions" : {
    "Group" : {
      "primaryKey" : "ABN",
      "required" : [ ],
      "rangeIndex" : [ ],
      "wordLexicon" : [ ],
      "properties" : {
        "ABN" : {
          "datatype" : "anyURI"
        },
        "Registered_Date" : {
          "datatype" : "dateTime"
        },
        "End_Date" : {
          "datatype" : "dateTime"
        },
```


Was using the UI in Chrome on a windows 10 pc although the quickstart app was hosted on a RedHat machine with Java 1.8 and DataHub 2.0.0-beta1

My fix btw was to just ssh into the server and add enough '}' characters to make it valid json

**Comment by damonfeldman** [comment]
Perhaps this is because we are writing to the file-system instead of MarkLogic. Not sure how it would work to track data transactionally in ML for safety and still write the configs to the file system for easy editing, but something to think about.

Separately, keeping one or more prior versions would make recovery easier.

**Comment by paxtonhare** [comment]
can't reproduce this.
