### ISSUE TITLE
Out of memory when flow has too many errors

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/marklogic-data-hub#543]
```
gradle hubrunflow -PentityName=blow-up -PflowName=do-it
:hubRunFlow
Running Flow: [blow-up:do-it]
        with batch size: 100
        with thread count: 4
        with Source DB: data-hub-STAGING
        with Destination DB: data-hub-FINAL
Expiring Daemon because JVM Tenured space is exhausted
Exception thrown by an onUrisReady listener
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
        at java.lang.String.<init>(String.java:207)
        at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:344)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:278)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:238)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:272)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:232)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl$FlowResource.run(FlowRunnerImpl.java:353)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl.lambda$run$8(FlowRunnerImpl.java:208)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl$$Lambda$33/576196594.processEvent(Unknown Source)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1$1.run(QueryBatcherImpl.java:671)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Daemon is stopping immediately JVM garbage collector thrashing and after running out of JVM memory
Expiring Daemon because JVM Tenured space is exhausted

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> Building 0% > :hubRunFlow%
```

Looks like the Vector of errormessages added in 2.0.0 is chewing up all the bits.

**Comment by damonfeldman** [comment]
For a large enough input, I can imagine a huge number of errors being acceptable. Is this too many errors in one batch, or in the entire run?

**Comment by paxtonhare** [comment]
it's the entire run. we are talking hundreds of thousands of errors.

@damonfeldman I'm thinking I should limit the number of errors returned to maybe 5. So return the 1st 5 and the total number that happened.

```
You had 234,550 errors. Here are the first 5:

stack dump
...
stack dump
```

sound good?

**Comment by paxtonhare** [comment]
@damonfeldman ping.
