### ISSUE TITLE
harmonize flow hangs without any logs after processing some documents

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/marklogic-data-hub#576]
I have about 23 million documents, I am trying to harmonize and after about 8 mil docs, the flow just hangs without any error logs.. 

But when I stop the flow and again restart say after 30mins to 1hr .,. it starts and works but again does this after certain amount of docs.. Do I need to clear anything after each document is processed so that I don;t see this behavior ? Is the Task server reaching it limit and will not take any more documents to process ?

**Comment by paxtonhare** [comment]
@ravi-b-m can you see in your AccessLog.txt in MarkLogic's data dir if the requests are still coming in or if they stall?

**Comment by damonfeldman** [comment]
It may also be useful to pull down the metrics exports from <ml-host>:8002/history. Zero in on "raw" data for the period for some minutes before the hang, and some minutes after the hang so we can see how MarkLogic loads and activities changed. This will help tell if it is lower request rates from the loader, or deadlocks in marklogic, or slow disks or what.

**Comment by popzip** [comment]
@ravi-b-m did this get resolved/should we close?

**Comment by ravi-b-m** [comment]
This is not resolved, now I have another strange issue, when I tell tp harmonize only one document only, the flow runs but the document is not written in the final database.. I see no errors in any log files.. 

```json
Output:
{
  "jobId" : "24475719-cd51-4e5a-9897-a0d1cf696d35",
  "flowType" : "harmonize",
  "flowName" : "harmonize-pubmed",
  "entityName" : "pubmed",
  "jobName" : null,
  "startTime" : "2017-11-28T16:21:05.740Z",
  "endTime" : "2017-11-28T16:21:07.990Z",
  "jobOutput" : null,
  "status" : "FINISHED",
  "successfulEvents" : 1,
  "failedEvents" : 0,
  "successfulBatches" : 1,
  "failedBatches" : 0
}
```

In the Access log
```log
10.229.5.240 - admin [28/Nov/2017:16:20:58 +0000] "HEAD /v1/ping?database=content-hub-STAGING HTTP/1.1" 204 0 - "okhttp/3.8.1"
10.229.5.240 - admin [28/Nov/2017:16:20:58 +0000] "POST /v1/resources/tracing?rs:enable=true&database=content-hub-STAGING HTTP/1.1" 200 155 - "okhttp/3.8.1"
10.229.5.240 - - [28/Nov/2017:16:21:05 +0000] "GET /v1/resources/flow?rs:flow-name=harmonize-pubmed&rs:flow-type=harmonize&rs:entity-name=pubmed&database=content-hub-STAGING HTTP/1.1" 401 104 - "okhttp/3.8.1"
10.229.5.240 - admin [28/Nov/2017:16:21:05 +0000] "GET /v1/resources/flow?rs:flow-name=harmonize-pubmed&rs:flow-type=harmonize&rs:entity-name=pubmed&database=content-hub-STAGING HTTP/1.1" 200 568 - "okhttp/3.8.1"
10.229.5.240 - - [28/Nov/2017:16:21:07 +0000] "POST /invoke XDBC/1.0" 401 0 - "Java/1.8.0_131 MarkLogicXCC/9.0-2"
10.229.5.240 - admin [28/Nov/2017:16:21:07 +0000] "POST /invoke XDBC/1.0" 200 131 - "Java/1.8.0_131 MarkLogicXCC/9.0-2"
10.229.5.240 - - [28/Nov/2017:16:21:07 +0000] "GET /v1/resources/forest-info?database=content-hub-STAGING HTTP/1.1" 401 104 - "okhttp/3.8.1"
10.229.5.240 - admin [28/Nov/2017:16:21:07 +0000] "GET /v1/resources/forest-info?database=content-hub-STAGING HTTP/1.1" 200 775 - "okhttp/3.8.1"
10.229.5.240 - admin [28/Nov/2017:16:21:07 +0000] "HEAD /v1/ping?database=content-hub-STAGING HTTP/1.1" 204 0 - "okhttp/3.8.1"
10.229.5.240 - admin [28/Nov/2017:16:21:07 +0000] "POST /v1/resources/flow?rs:job-id=24475719-cd51-4e5a-9897-a0d1cf696d35&rs:flow-name=harmonize-pubmed&rs:target-database=content-hub-FINAL&rs:options={%22dhf.startPMID%22:%221040001%22,%22dhf.endPMID%22:%221040002%22,%22entity%22:%22pubmed%22,%22flow%22:%22harmonize-pubmed%22,%22flowType%22:%22harmonize%22}&rs:entity-name=pubmed&rs:identifiers=/pubmed/1040001.xml&database=content-hub-STAGING HTTP/1.1" 200 244 - "okhttp/3.8.1"
```

**Comment by ravi-b-m** [comment]
Today I did again 10 mill and the harmonize flow hung after 2mil.. I am attaching the metrics file.
[metrics-20171130-190344.xlsx](https://github.com/marklogic-community/marklogic-data-hub/files/1519146/metrics-20171130-190344.xlsx)

**Comment by paxtonhare** [comment]
Try turning on Debugging to see if any errors show up.

./gradlew hubEnableDebugging

or

go to the settings page in Quickstart and turn it on.

**Comment by ravi-b-m** [comment]
Update, I ran the harmonize flow on my windows box and increased the batch size to 1000 and thead count to 8.. After 9 million docs I get the following error

```java
Exception thrown by an onUrisReady listener
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
        at java.lang.StringBuilder.append(StringBuilder.java:202)
        at com.burgstaller.okhttp.digest.fromhttpclient.BasicHeaderValueFormatter.doFormatValue(BasicHeaderValueFormatter.java:59)
        at com.burgstaller.okhttp.digest.fromhttpclient.BasicHeaderValueFormatter.formatNameValuePair(BasicHeaderValueFormatter.java:34)
        at com.burgstaller.okhttp.digest.DigestAuthenticator.createDigestHeader(DigestAuthenticator.java:469)
        at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticateWithState(DigestAuthenticator.java:246)
        at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticateWithState(DigestAuthenticator.java:205)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:40)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:674)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:669)
        at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:3981)
        at com.marklogic.client.impl.OkHttpServices.access$1200(OkHttpServices.java:164)
        at com.marklogic.client.impl.OkHttpServices$25.apply(OkHttpServices.java:3764)
        at com.marklogic.client.impl.OkHttpServices$25.apply(OkHttpServices.java:3762)
        at com.marklogic.client.impl.OkHttpServices.sendRequestWithRetry(OkHttpServices.java:698)
        at com.marklogic.client.impl.OkHttpServices.postIteratedResourceImpl(OkHttpServices.java:3768)
        at com.marklogic.client.impl.OkHttpServices.postIteratedResource(OkHttpServices.java:3730)
        at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:99)
        at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:95)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl$FlowResource.run(FlowRunnerImpl.java:345)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl.lambda$run$8(FlowRunnerImpl.java:208)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl$$Lambda$8/1878174254.processEvent(Unknown Source)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1$1.run(QueryBatcherImpl.java:671)
        at java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy.rejectedExecution(ThreadPoolExecutor.java:2022)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)

```

**Comment by popzip** [comment]
@paxtonhare @aebadirad is this worth re-try after 2.0.3 release?

**Comment by aebadirad** [comment]
Yes. This should be resolved for 2.0.3.

**Comment by dmcassel** [comment]
Need to re-follow up with and triage this one.

could also be related to long list of URIs?

Pending URI #633 fix - test 2.0.3

**Comment by popzip** [comment]
@ravi-b-m please let us know if you can retry on latest release.
