### ISSUE TITLE
Running harmonized flow from gradle causes authorization error

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/marklogic-data-hub#581]
When I am running harmonized flow from gradle I get the following error
`previous digest authentication with same nonce failed, returning null `

This was working fine and suddenly it started to come.. how can I clear `nonce` counter ? Following is the full trace of the exception
```java
previous digest authentication with same nonce failed, returning null
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/flow: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4257)
        at com.marklogic.client.impl.OkHttpServices.postIteratedResourceImpl(OkHttpServices.java:3771)
        at com.marklogic.client.impl.OkHttpServices.postIteratedResource(OkHttpServices.java:3730)
        at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:99)
        at com.marklogic.client.impl.ResourceServicesImpl.post(ResourceServicesImpl.java:95)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl$FlowResource.run(FlowRunnerImpl.java:345)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl.lambda$run$8(FlowRunnerImpl.java:208)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl$1$1.run(QueryBatcherImpl.java:671)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

Following is what I see in the logfiles, when I enabled tracing and debugging

```
2017-11-20 15:08:48.134 Info:+################################################################
2017-11-20 15:08:48.134 Info:+REQUEST DETAILS:
2017-11-20 15:08:48.134 Info:+
2017-11-20 15:08:48.134 Info:+  [POST]  /invoke
2017-11-20 15:08:48.134 Info:+
2017-11-20 15:08:48.134 Info:+  [Headers]
2017-11-20 15:08:48.134 Info:+    Content-Type => application/x-www-form-urlencoded
2017-11-20 15:08:48.134 Info:+    Authorization => Digest username="admin", realm="public", nonce="f5143e41ab5306e15f7c328c2c340493", uri="/invoke", qop="auth", nc="1", cnonce="35beef15d41f407c3f41f3e8f24647d9", response="c9d767336fc5988283fe6cca9dcb9dc3", opaque="343c01db9d11d0f0"
2017-11-20 15:08:48.134 Info:+    User-Agent => Java/1.8.0_131 MarkLogicXCC/9.0-2
2017-11-20 15:08:48.134 Info:+    Accept => application/vnd.marklogic.sequence, */*
2017-11-20 15:08:48.134 Info:+    Content-Length => 526
2017-11-20 15:08:48.134 Info:+    Connection => keep-alive
2017-11-20 15:08:48.134 Info:+
2017-11-20 15:08:48.134 Info:+  [Request Params]
2017-11-20 15:08:48.134 Info:+    module => /com.marklogic.hub/endpoints/collector.xqy
2017-11-20 15:08:48.134 Info:+    locale => en_US
2017-11-20 15:08:48.134 Info:+    tzoffset => -21600
2017-11-20 15:08:48.134 Info:+    dbname => content-hub-STAGING
2017-11-20 15:08:48.134 Info:+    evn0 => 
2017-11-20 15:08:48.134 Info:+    evl0 => job-id
2017-11-20 15:08:48.134 Info:+    evt0 => xs:string
2017-11-20 15:08:48.134 Info:+    evv0 => 19b141d9-6a33-4fbe-b790-8cfe870e9e41
2017-11-20 15:08:48.134 Info:+    evn1 => 
2017-11-20 15:08:48.134 Info:+    evl1 => entity-name
2017-11-20 15:08:48.134 Info:+    evt1 => xs:string
2017-11-20 15:08:48.134 Info:+    evv1 => pubmed
2017-11-20 15:08:48.134 Info:+    evn2 => 
2017-11-20 15:08:48.134 Info:+    evl2 => options
2017-11-20 15:08:48.134 Info:+    evt2 => xs:string
2017-11-20 15:08:48.134 Info:+    evv2 => {"dhf.startPMID":"1040000\n","dhf.endPMID":"1040001","entity":"pubmed","flow":"harmonize-pubmed","flowType":"harmonize"}
2017-11-20 15:08:48.134 Info:+    evn3 => 
2017-11-20 15:08:48.134 Info:+    evl3 => flow-name
2017-11-20 15:08:48.134 Info:+    evt3 => xs:string
2017-11-20 15:08:48.134 Info:+    evv3 => harmonize-pubmed
2017-11-20 15:08:48.134 Info:+
2017-11-20 15:08:48.134 Info:+  [Body]
2017-11-20 15:08:48.134 Info:+  document{binary{""}}
2017-11-20 15:08:48.134 Info:+
2017-11-20 15:08:48.134 Info:+################################################################
2017-11-20 15:08:48.206 Info: PERFORMANCE: /v1/resources/collector:post took PT0.072514S
2017-11-20 15:08:48.366 Info: 
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+################################################################
2017-11-20 15:08:48.366 Info:+REQUEST DETAILS:
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+  **FOREST INFO**
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+  [GET]  /v1/resources/forest-info?
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+  [Headers]
2017-11-20 15:08:48.366 Info:+    Accept => application/json
2017-11-20 15:08:48.366 Info:+    ML-Agent-ID => java
2017-11-20 15:08:48.366 Info:+    Authorization => Digest username="admin", realm="public", nonce="d4d45a3f6c9c03ca1a291e8be00c33ad", uri="/v1/resources/forest-info?database=content-hub-STAGING", response="30da11ee65356afd74dc6910d4c294ac", qop=auth, nc=00000001, cnonce="1901f78e85ad08d7", algorithm=MD5, opaque="6462a1da4f943ac9"
2017-11-20 15:08:48.366 Info:+    Host => 10.239.12.158:8010
2017-11-20 15:08:48.366 Info:+    Connection => Keep-Alive
2017-11-20 15:08:48.366 Info:+    Accept-Encoding => gzip
2017-11-20 15:08:48.366 Info:+    User-Agent => okhttp/3.8.1
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+  [Request Params]
2017-11-20 15:08:48.366 Info:+    database => content-hub-STAGING
2017-11-20 15:08:48.366 Info:+    name => forest-info
2017-11-20 15:08:48.366 Info:+
2017-11-20 15:08:48.366 Info:+################################################################
```

**Comment by ravi-b-m** [comment]
When I run on a different computer it worked fine .. so I am assuming it has to do with local variables getting messed up ...

**Comment by dmcassel** [comment]
Sounds like this is a non-issue, so we'll close it.
