### ISSUE TITLE
gradle tasks broken in 2.0.1

### ISSUE THREAD

**Issue by joecrean** [marklogic-community/marklogic-data-hub#599]
#### The issue

If i create a build.gradle file as in the examples/barebones and run mlHubinit then i see the following exception

```
[creanjx.DE2LS-D0Q1YW1] ➤ ./gradlew hubInit

FAILURE: Build failed with an exception.

* What went wrong:
tried to access method com.marklogic.hub.HubConfig.loadConfigurationFromProperties(Ljava/util/Properties;)V from class com.marklogic.hub.DefaultHubConfigFactory
```
I see this effect even with `gradlew tasks`.

What behavior are you expecting?

It should run through without an issue - if i set the data hub dependancy to 2.0.0 then i see the following

```[creanjx.DE2LS-D0Q1YW1] ➤ ./gradlew hubInit
MISSING PROPERTY mlRestAdminUsername or mlUsername
MISSING PROPERTY mlRestAdminPassword or mlPassword
:hubInit


############################################
# Your Data Hub Framework Project is ready.
############################################

 - Set username and password
     There are several ways to do this. The easiest is to set mlUsername and mlPassword in gradle.properties.
     For other approaches see: https://github.com/marklogic-community/marklogic-data-hub/wiki/Password-Management
```

#### Tech details

Which Operating System are you using? Windows 7 but have seen it on CentOS 7 too.

Which version of MarkLogic are you using? 9.0-3.1

Which version of the Data Hub Framework are you using? 2.0.1

Is this a QuickStart UI bug? If so, which browser are you using? 

#### The devil is in the details...
```
[creanjx.DE2LS-D0Q1YW1] ➤ ./gradlew hubInit --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
tried to access method com.marklogic.hub.HubConfig.loadConfigurationFromProperties(Ljava/util/Properties;)V from class com.marklogic.hub.DefaultHubConfigFactory

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalAccessError: tried to access method com.marklogic.hub.HubConfig.loadConfigurationFromProperties(Ljava/util/Properties;)V from class com.marklogic.hub.DefaultHubConfigFactory
        at com.marklogic.hub.DefaultHubConfigFactory.newHubConfig(DefaultHubConfigFactory.java:37)
        at com.marklogic.hub.DefaultHubConfigFactory$newHubConfig.call(Unknown Source)
        at com.marklogic.gradle.DataHubPlugin.initializeProjectExtensions(DataHubPlugin.groovy:68)
        at com.marklogic.gradle.DataHubPlugin$initializeProjectExtensions.callCurrent(Unknown Source)
        at com.marklogic.gradle.DataHubPlugin.apply(DataHubPlugin.groovy:36)
        at com.marklogic.gradle.DataHubPlugin.apply(DataHubPlugin.groovy)

```
```
15:21:32.277 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlDeploySecurity for replacing module tokens
15:21:32.277 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlAdminConfig for replacing module tokens
15:21:32.278 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlDeployCpf for replacing module tokens
15:21:32.278 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlCreateTransform for replacing module tokens
15:21:32.279 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlReloadModules for replacing module tokens
15:21:32.279 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlFinalDbName for replacing module tokens
15:21:32.279 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlHost for replacing module tokens
15:21:32.279 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlJobAuth for replacing module tokens
15:21:32.280 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlClearSchemasDatabase for replacing module tokens
15:21:32.280 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlSetCollections for replacing module tokens
15:21:32.280 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlDeployProtectedCollections for replacing module tokens
15:21:32.281 [DEBUG] [com.marklogic.gradle.ProjectPropertySource] Including key mlTemporalCommands for replacing module tokens
15:21:32.289 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 3.284 secs
15:21:32.296 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
15:21:32.297 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
15:21:32.297 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
15:21:32.298 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 9.302 secs
15:21:32.311 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
15:21:32.315 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
15:21:32.315 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.01 secs
15:21:32.316 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Plugin Resolution Cache (C:\Users\creanjx\.gradle\caches\3.4\plugin-resolution)
15:21:32.316 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache plugin-use-metadata.bin (C:\Users\creanjx\.gradle\caches\3.4\plugin-resolution\plugin-use-metadata.bin)
15:21:32.317 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Plugin Resolution Cache (C:\Users\creanjx\.gradle\caches\3.4\plugin-resolution).
15:21:32.321 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
15:21:32.321 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
15:21:32.322 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Generated Gradle JARs cache (C:\Users\creanjx\.gradle\caches\3.4\generated-gradle-jars) was closed 0 times.
15:21:32.322 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for artifact cache (C:\Users\creanjx\.gradle\caches\modules-2)
15:21:32.323 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (C:\Users\creanjx\.gradle\caches\modules-2\metadata-2.23\artifact-at-repository.bin)
15:21:32.323 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (C:\Users\creanjx\.gradle\caches\modules-2\metadata-2.23\module-metadata.bin)
15:21:32.324 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (C:\Users\creanjx\.gradle\caches\modules-2).
15:21:32.327 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
15:21:32.480 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@7f28f789
15:21:32.481 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 13: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
15:21:32.485 [INFO] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: tried to access method com.marklogic.hub.HubConfig.loadConfigurationFromProperties(Ljava/util/Properties;)V from class com.marklogic.hub.DefaultHubConfigFactory] from daemon DaemonInfo{pid=12548, address=[e5082f7b-a231-4616-90af-831c91a6692a port:62198, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1512397217632, context=DefaultDaemonContext[uid=db24a87c-09af-4932-8893-b7de5e167909,javaHome=C:\Java\jdk-8.0u152,daemonRegistryDir=C:\Users\creanjx\.gradle\daemon,pid=12548,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=DE,-Duser.language=de,-Duser.variant]} (build should be done).
15:21:32.486 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
15:21:32.491 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop

```

**Comment by paxtonhare** [comment]
@joecrean Don't use 2.0.1. It's a broken build. Upgrade immediately to 2.0.2
