### ISSUE TITLE
Collector's disk queue is filling up

### ISSUE THREAD

**Issue by kmoralesml** [marklogic-community/marklogic-data-hub#601]
1. The issue

Short description of the problem:
I am running an harmonize flow against a fairly large set of STAGING documents.
The collector gathers uri’s using a set of criteria (cts:query as passed into the cts:uris).

I ran the harmonize flow, constraining the returned uris from [1 to 1000000] – so far so good on 1 million.  No errors, job completed (my writer#write is a no-op for now)
I ran the harmonize flow, constraining the returned uris from [1 to 5000000] – so far so good on 5 million.  No errors, job completed (my writer#write is a no-op for now)

I then ran the harmonize flow, without constraining the returned uris – beforehand, in query console, I did an fn:count.  I expect ~88 million documents that fit the criteria (out of 151 million documents), and thus expect 88 million uris.

The flow ran for a good while until throwing an exception (see below)

What behavior are you expecting?
I expect the queue full state to be well handled or some recommendation on tuning and/or ensuring enough space is available for writing 88 million + uris to disk.

      1. Tech details

Which Operating System are you using?
Linux ip-xx-xxx-xx-xx 4.4.44-39.55.amzn1.x86_64 #1 SMP Mon Jan 30 18:15:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Which version of MarkLogic are you using?
9.0-2

Which version of the Data Hub Framework are you using?
2.0.0 FINAL

Is this a QuickStart UI bug? If so, which browser are you using?
No

      1. The devil is in the details...
:hubRunFlow
Running Flow: [xxx-xxxxxxx:harmonize-xxx-xxxxxxx]
with batch size: 100
with thread count: 16
with Source DB: xxx-xxx-xxx-data-hub-STAGING
with Destination DB: xxx-xxx-xxx-data-hub-FINAL
Error writing to DiskQueue backing store
java.lang.IllegalStateException: Queue full
at java.util.AbstractQueue.add(AbstractQueue.java:98)
at com.marklogic.hub.collector.impl.CollectorImpl.run(CollectorImpl.java:80)
at com.marklogic.hub.flow.impl.FlowRunnerImpl.run(FlowRunnerImpl.java:178)
at com.marklogic.hub.flow.FlowRunner$run$7.call(Unknown Source)
at com.marklogic.gradle.task.RunFlowTask.runFlow(RunFlowTask.groovy:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)

┆Status: To Do

**Comment by dmcassel** [comment]
Is there any more information in the MarkLogic app server's error log (probably 8010_ErrorLog.txt)?

**Comment by kmoralesml** [comment]
Dear Dave,
No, unfortunately, there aren't any entries in the app server log for STAGING.  I also checked ErrorLog.txt and log entries did NOT got emitted there either when the client threw the queue full exception...
-K

**Comment by kmoralesml** [comment]
I am attaching the full stack trace from the gradle task.  The task oddly is reported as successful.
[issue601Repeat88MilFullStackTrace.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1548422/issue601Repeat88MilFullStackTrace.txt)

**Comment by dmcassel** [comment]
did you mean to close this issue?

**Comment by kmoralesml** [comment]
Sorry, I inadvertently closed it when I attached full stack trace.

**Comment by paxtonhare** [comment]
I noticed that the logger for the DiskQueue class isn't jiving with the logger for the rest of the app. Important error info isn't being logged. We should fix that so we can see the issues.

I'm curious to see if this happens when disk space runs out. If you are queueing 88 bazillion uris, they are being streamed into a disk backed queue. if the disk runs out then this will certainly fail.

@kmoralesml we may need to work with you once we have the logger fixed so we can see exactly why your code is failing.

**Comment by kmoralesml** [comment]
Hi,  I retried the flow, collecting the same 88 bazillion uris.  This time, I **redirected the gradle tmp space** to a directory in another volume that has bazillion of space, i.e. gradle -Djava.io.tmpdir=/space/plenty/gradletmp/ .  I got past the queue full exception.  However, a new exception surfaced, com.marklogic.xcc.exceptions.XQueryException: XDMP-TOOMUCHTEXT.  See attached.
[all_collector_20171211104905.log](https://github.com/marklogic-community/marklogic-data-hub/files/1548728/all_collector_20171211104905.log).
Unlike the queue full exception, this one did manifest itself in the app server log
[8050_ErrorLog.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1548741/8050_ErrorLog.txt)

For now, I am not blocked.  I have 2 non-mutually exclusive mitigation routes:
* override tmp directory
* modify the collector such that it collects chunks of uri's, taking a custom dhf parameter to inject some rule, i.e. a range or modulo (the uri scheme has a numeric component to it so I can take advantage of that, and did just that in a previous project)

**Comment by dmcassel** [comment]
Pending fix for #633

**Comment by popzip** [comment]
@kmoralesml can you try this again on latest release?

**Comment by kmoralesml** [comment]
Hi, 
I tried this again with DHF 2.04 and ML 9.0-4.  Bug is no longer happening.
However, I am now observing #658  .  Note: **DHF Tracing _is_ disabled.**



Kristina
