### ISSUE TITLE
Unable to create Harmonize Flow

### ISSUE THREAD

**Issue by ayuwono** [marklogic-community/marklogic-data-hub#637]
ML version: 9.0 Dec 15

I'm following the quickstart tutorial and it seems that I can't create Harmonize Flow.

Step: https://marklogic-community.github.io/marklogic-data-hub/tutorial/harmonizing-product-data/

This error is thrown after I clicked on Create

16:53:50.695 [http-nio-8080-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() fo                                                                                                 r servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; ne                                                                                                 sted exception is com.marklogic.client.FailedRequestException: Local message: failed to read resourc                                                                                                 e at resources/scaffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOE                                                                                                 R0000) Invalid request:  reason: Extension scaffold-content or a dependency does not exist: XDMP-MOD                                                                                                 NOTFOUND: (err:XQST0059) Module /MarkLogic/entity-services/entity-services-impl.xqy not found . See                                                                                                  the MarkLogic server error log for further detail.] with root cause
com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/sca                                                                                                 ffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid req                                                                                                 uest:  reason: Extension scaffold-content or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQS                                                                                                 T0059) Module /MarkLogic/entity-services/entity-services-impl.xqy not found . See the MarkLogic serv                                                                                                 er error log for further detail.
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4257)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3036                                                                                                 )
        at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3013)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
        at com.marklogic.hub.scaffold.Scaffolding$ContentPlugin.getContents(Scaffolding.java:432)
        at com.marklogic.hub.scaffold.Scaffolding.createFlow(Scaffolding.java:99)
        at com.marklogic.quickstart.service.EntityManagerService.createFlow(EntityManagerService.jav                                                                                                 a:321)
        at com.marklogic.quickstart.web.EntitiesController.createFlow(EntitiesController.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMe                                                                                                 thod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableH                                                                                                 andlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invok                                                                                                 eAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invoke                                                                                                 HandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handle                                                                                                 Internal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHa                                                                                                 ndlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970                                                                                                 )
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(Appli                                                                                                 cationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestT                                                                                                 raceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(Filter                                                                                                 SecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(Filt                                                                                                 erSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTran                                                                                                 slationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManageme                                                                                                 ntFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(An                                                                                                 onymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFil                                                                                                 ter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCac                                                                                                 heAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.do                                                                                                 Filter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter                                                                                                 .java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterF                                                                                                 ilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(Securi                                                                                                 tyContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.d                                                                                                 oFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:                                                                                                 214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy                                                                                                 .java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:                                                                                                 262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter                                                                                                 .java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormConte                                                                                                 ntFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFi                                                                                                 lter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncoding                                                                                                 Filter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilt                                                                                                 er.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
16:53:58.076 [SimpleAsyncTaskExecutor-7] INFO  com.marklogic.hub.EntityManager - min modified: 15151                                                                                                 99878303
16:53:58.179 [SimpleAsyncTaskExecutor-7] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHub                                                                                                 Service.installUserModules took 0.196201174s
16:53:58.666 [SimpleAsyncTaskExecutor-6] INFO  com.marklogic.hub.EntityManager - min modified: 15151                                                                                                 99878303
16:54:03.561 [SimpleAsyncTaskExecutor-6] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHub                                                                                                 Service.installUserModules took 12.591819936s
16:54:18.681 [http-nio-8080-exec-10] INFO  c.marklogic.hub.scaffold.Scaffolding - writing: scaffoldi                                                                                                 ng/harmonize/sjs/collector.sjs => C:\builds\win64\b9_0\data-hub\plugins\entities\Product\harmonize\H                                                                                                 armonize Products\collector.sjs
16:54:18.684 [http-nio-8080-exec-10] INFO  c.marklogic.hub.scaffold.Scaffolding - writing: scaffoldi                                                                                                 ng/harmonize/sjs/writer.sjs => C:\builds\win64\b9_0\data-hub\plugins\entities\Product\harmonize\Harm                                                                                                 onize Products\writer.sjs
16:54:23.862 [http-nio-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() f                                                                                                 or servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; n                                                                                                 ested exception is com.marklogic.client.FailedRequestException: Local message: failed to read resour                                                                                                 ce at resources/scaffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FO                                                                                                 ER0000) Invalid request:  reason: Extension scaffold-content or a dependency does not exist: XDMP-MO                                                                                                 DNOTFOUND: (err:XQST0059) Module /MarkLogic/entity-services/entity-services-impl.xqy not found . See                                                                                                  the MarkLogic server error log for further detail.] with root cause
com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/sca                                                                                                 ffold-content: Internal Server Error. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid req                                                                                                 uest:  reason: Extension scaffold-content or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQS                                                                                                 T0059) Module /MarkLogic/entity-services/entity-services-impl.xqy not found . See the MarkLogic serv                                                                                                 er error log for further detail.
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4257)
        at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3036                                                                                                 )
        at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3013)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
        at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
        at com.marklogic.hub.scaffold.Scaffolding$ContentPlugin.getContents(Scaffolding.java:432)
        at com.marklogic.hub.scaffold.Scaffolding.createFlow(Scaffolding.java:99)
        at com.marklogic.quickstart.service.EntityManagerService.createFlow(EntityManagerService.jav                                                                                                 a:321)
        at com.marklogic.quickstart.web.EntitiesController.createFlow(EntitiesController.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMe                                                                                                 thod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableH                                                                                                 andlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invok                                                                                                 eAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invoke                                                                                                 HandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handle                                                                                                 Internal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHa                                                                                                 ndlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970                                                                                                 )
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(Appli                                                                                                 cationContextHeaderFilter.java:55)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestT                                                                                                 raceFilter.java:110)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(Filter                                                                                                 SecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(Filt                                                                                                 erSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTran                                                                                                 slationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManageme                                                                                                 ntFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(An                                                                                                 onymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFil                                                                                                 ter(SecurityContextHolderAwareRequestFilter.java:170)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCac                                                                                                 heAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.do                                                                                                 Filter(AbstractAuthenticationProcessingFilter.java:200)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter                                                                                                 .java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterF                                                                                                 ilter.java:64)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(Securi                                                                                                 tyContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.d                                                                                                 oFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChain                                                                                                 Proxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:                                                                                                 214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy                                                                                                 .java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:                                                                                                 262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter                                                                                                 .java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormConte                                                                                                 ntFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFi                                                                                                 lter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncoding                                                                                                 Filter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilt                                                                                                 er.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:10                                                                                                 7)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.j                                                                                                 ava:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)

**Comment by dmcassel** [comment]
Was this with Quick Start 2.0.2?

**Comment by grechaw** [comment]
This is more likely to be an issue with entity services build integration.  Even since this bug, Shiva may have changed the build scripts such that this no longer happens.

My guess is that this was locally-built system and this will not happen wit more recent builds.

**Comment by ayuwono** [comment]
Yes it's on quickstart 2.0.2

**Comment by kkanthet** [comment]
I see below failure starting today's nightly 
result.output.contains('sourceDB must be a valid name')
|      |      |
|      |      false
|      :hubCreateHarmonizeFlow FAILED
|       
|      FAILURE: Build failed with an exception.
|       
|      * What went wrong:
|      Execution failed for task ':hubCreateHarmonizeFlow'.
|      > flowName property is required. Supply the parameter with -PflowName=Yourentity
|       
|      * Try:
|      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
|       
|      BUILD FAILED

**Comment by aebadirad** [comment]
The above is actually another issue, relating to a test I wrote, and I'll address that shortly here. It shouldn't impact the original issue.

**Comment by paxtonhare** [comment]
@ayuwono were you using a ML nightly?

**Comment by ayuwono** [comment]
I was using ML nightly (build Dec 18) and it's on Windows 7. I know this is a long time ago. I went through tutorial on more recent build (Jan 8) on Mac and it was fine

**Comment by paxtonhare** [comment]
ok. I had noticed a problem where entity-services wasn't being included in nightlies. I'm going to close this ticket since I don't think it's a DHF issue.
