### ISSUE TITLE
Collector throws null pointer exception when there is nothing to process

### ISSUE THREAD

**Issue by venuiyengar** [marklogic-community/marklogic-data-hub#735]
When I run the harmonization flows with 2.0.3 I am getting null pointer exception and I cannot figure out what is causing this. I looked at the collectorImpl and I do not understand why I am seeing this exception. This may be coming from options map and not sure.

I think it generates null pointer exception when there is nothing to process from the collector (collector does not return anything). How can we fix this so that it does not throw null pointer exception.

java.lang.NullPointerException
 
        at com.marklogic.hub.collector.impl.CollectorImpl.run(CollectorImpl.java:123)
        at com.marklogic.hub.flow.impl.FlowRunnerImpl.run(FlowRunnerImpl.java:185)
        at com.roche.dch.listeners.GenericHarmonizationListener.runHarmonization(GenericHarmonizationListener.java:106)
        at com.roche.dch.listeners.GenericHarmonizationListener.runHamonizationWithTiming(GenericHarmonizationListener.java:148)
        at com.roche.dch.listeners.GenericCompletionNotificationListener.processAuditsStaleStep(GenericCompletionNotificationListe
ner.java:635)
        at com.roche.dch.listeners.GenericCompletionNotificationListener.postIngestionStepProcess(GenericCompletionNotificationLis
tener.java:509)
        at com.roche.dch.listeners.GenericCompletionNotificationListener.afterJob(GenericCompletionNotificationListener.java:181)
        at org.springframework.batch.core.listener.CompositeJobExecutionListener.afterJob(CompositeJobExecutionListener.java:60)

**Comment by aebadirad** [comment]
Confirmed bug
