### ISSUE TITLE
MLCPBean doesn't have -ssl option

### ISSUE THREAD

**Issue by srinathgit** [marklogic-community/marklogic-data-hub#760]
I am trying to run the tests on SSL enabled servers. For input flows using mlcp, MLCPBean has the list of MLCP options. The -ssl option used for running mlcp against SSL servers seems to be missing from that class.
```
Exception in thread "Thread-1" 09:27:22.948 [main] ERROR com.marklogic.hub.HubTestBase - 
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field ""ssl"" (class com.marklogic.contentpump.bean.MlcpBean), not marked as ignorable (84 known properties: "port", "delimited_root_name", "document_selector", "delimiter", "directory_filter", "aggregate_record_element", "output_graph", "filename_as_collection", "input_compressed", "output_password", "thread_count", "password", "type_filter", "transform_module", "generate_uri", "mode", "conf", "output_host", "host", "input_username", "output_partition", "data_type", "archive_metadata_optional", "copy_quality", "output_type", "collection_filter", "copy_permissions", "copy_properties", "max_split_size", "fastload", "output_uri_prefix", "snapshot", "output_permissions", "input_compression_codec", "output_file_path", "command", "hadoop_conf_dir", "uri_id", "query_filter", "input_database", "input_file_path", "output_username", "username", "output_collections", "content_encoding", "namespace", "document_type", "compress", "split_input", "batch_size", "input_file_type", "aggregate_record_namespace", "input_password", "tolerate_errors", "additionalOptions", "output_database", "transform_param" [truncated]])
 at [Source: UNKNOWN; line: ~~1, column:~~ 1] (through reference chain: com.marklogic.contentpump.bean.MlcpBean[""ssl""])
	at com.marklogic.hub.util.MlcpRunner.run(MlcpRunner.java:101)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field ""ssl"" (class com.marklogic.contentpump.bean.MlcpBean), not marked as ignorable (84 known properties: "port", "delimited_root_name", "document_selector", "delimiter", "directory_filter", "aggregate_record_element", "output_graph", "filename_as_collection", "input_compressed", "output_password", "thread_count", "password", "type_filter", "transform_module", "generate_uri", "mode", "conf", "output_host", "host", "input_username", "output_partition", "data_type", "archive_metadata_optional", "copy_quality", "output_type", "collection_filter", "copy_permissions", "copy_properties", "max_split_size", "fastload", "output_uri_prefix", "snapshot", "output_permissions", "input_compression_codec", "output_file_path", "command", "hadoop_conf_dir", "uri_id", "query_filter", "input_database", "input_file_path", "output_username", "username", "output_collections", "content_encoding", "namespace", "document_type", "compress", "split_input", "batch_size", "input_file_type", "aggregate_record_namespace", "input_password", "tolerate_errors", "additionalOptions", "output_database", "transform_param" [truncated]])
 at [Source: UNKNOWN; line: ~~1, column:~~ 1] (through reference chain: com.marklogic.contentpump.bean.MlcpBean[""ssl""])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1292)
	at com.marklogic.hub.util.MlcpRunner.run(MlcpRunner.java:76)
```

┆Status: To Do

**Comment by srinathgit** [comment]
For tests with SSL enabled servers, EndToEndFlowTests will not be running tests using mlcp for input flows for now

**Comment by dmcassel** [comment]
have requested a fix in mlcp-util

**Comment by srinathgit** [comment]
I think we need to add "-restrict_hosts" to MLCPBean as well. For scenarios where the cluster has one e-node and 2 d-nodes, we might want restrict the hosts to which MLCP talks to.

**Comment by popzip** [comment]
is this a change for mlcp? @srinathgit

**Comment by srinathgit** [comment]
These  options have been added to mlcp-util as a part of https://github.com/marklogic-community/mlcp-util/commit/a165e900c68534001d54803e428bcbc3d54b46fc. The issue has been closed in mlcp-util (https://github.com/marklogic-community/mlcp-util/issues/3). I ran mlcp with ssl and the input flows ran fine. So, I think this issue can be closed
