### ISSUE TITLE
Code edited externally not updating on quickstart editor windows

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-data-hub#795]
#### The issue
Old code is still displaying in a harmonize flow content.xqy editor panel.
This persists even if I refresh the web page.

#### Tech details

Which Operating System are you using?
osx

Which version of MarkLogic are you using?
9.0-3.1

Which version of the Data Hub Framework are you using?
2.0-4

Is this a QuickStart UI bug? If so, which browser are you using?
unsure

## Stack Trace
The QuickStart Java console has this stack trace (which may or may not be related to this bug)
15:03:07.871 [SimpleAsyncTaskExecutor-39] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.marklogic.quickstart.service.DataHubService.installUserModulesAsync(com.marklogic.hub.HubConfig,boolean,com.marklogic.quickstart.listeners.DeployUserModulesListener,com.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Local message: failed to read resource at resources/validate: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $uri as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail.
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:97)
	at com.marklogic.quickstart.service.DataHubService.installUserModulesAsync(DataHubService.java:87)
	at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/validate: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $uri as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4317)
	at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3081)
	at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3058)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
	at com.marklogic.hub.validate.EntitiesValidator.validateAll(EntitiesValidator.java:21)
	at com.marklogic.quickstart.service.DataHubService.validateUserModules(DataHubService.java:139)
	at com.marklogic.quickstart.service.DataHubService.installUserModules(DataHubService.java:95)
	... 8 common frames omitted
15:03:10.302 [SimpleAsyncTaskExecutor-38] INFO  c.m.hub.util.PerformanceLogger - PERFORMANCE: DataHubService.installUserModules took 6.7553227s
15:03:27

**Comment by damonfeldman** [comment]
Redeploying modules or logging out and back in from the GUI (quickstart) also does not fix the bug.

**Comment by damonfeldman** [comment]
This was due to copying content.xqy and it was actually a copy that was showing in the editor windows.
