### ISSUE TITLE
QuickStart Browse Data throws XDMP-LEXVAL

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/marklogic-data-hub#797]
Walking through the tutorial, I got to the [Browse and Understand Data](https://marklogic-community.github.io/marklogic-data-hub/tutorial/browse-understand-product-data/) step. After bringing up the Browse view, I clicked the "Entities Only" checkbox (because stupid people do stupid things, and it was highlighted in the in screenshot in tutorial).

This caused QuickStart to "hang" because the server threw an exception. Likely because no entities yet exist at this point in the tutorial, AFAIK. As such, this is a "don't put beans up your nose" problem, but I thought I should mention it.

- ML version: Some random 9.0 nightly in the run up to 9.0-5.
- OS: Server on RHEL, QuickStart 2.0.4 on Windows.
- Browser: Chrome

Error and partial stack trace below:
```
11:07:38.425 [http-nio-8080-exec-4] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] 
  - Servlet.service() for servlet [dispatcherServlet] in context with path [] 
  threw exception [Request processing failed; nested exception is 
  com.marklogic.client.FailedRequestException: Local message: search failed: 
  Bad Request. Server Message: XDMP-LEXVAL: cts:qname("*:instance") -- Invalid 
  lexical value "*:instance"] with root cause
com.marklogic.client.FailedRequestException: Local message: search failed: 
  Bad Request. Server Message: XDMP-LEXVAL: cts:qname("*:instance") -- Invalid lexical value "*:instance"
        at com.marklogic.client.impl.OkHttpServices$OkHttpSearchRequest.getResponse(OkHttpServices.java:2274)
        at com.marklogic.client.impl.OkHttpServices.search(OkHttpServices.java:2051)
        at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:175)
        at com.marklogic.client.impl.QueryManagerImpl.search(QueryManagerImpl.java:147)
        at com.marklogic.quickstart.service.SearchService.search(SearchService.java:104)
        at com.marklogic.quickstart.service.SearchService$$FastClassBySpringCGLIB$$ca9341e5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:13
3)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at com.marklogic.quickstart.service.SearchService$$EnhancerBySpringCGLIB$$ff5049fd.search(<generated>)
        at com.marklogic.quickstart.web.SearchController.search(SearchController.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by kcoleman-marklogic** [comment]
Sorry, that was actual DHF v2.0.3, not 2.0.4, but I'm guessing you already knew that.  Sorry for being a dingbat.

**Comment by popzip** [comment]
does that mean its not there anymore?

**Comment by kcoleman-marklogic** [comment]
IDK, has 2.0.4 been released? 2.0.3 is what I got when I followed the download instructions in the DHF tutorial, so I assumed it's the latest.

**Comment by popzip** [comment]
Oh man. I'm not sure if related so i will leave this one open but we need to update the tutorial link (will file separately). 

2.0.4 _is_ out (https://github.com/marklogic-community/marklogic-data-hub/releases).

Possibly you are hitting this bug which was fixed in 2.0.4? https://github.com/marklogic-community/marklogic-data-hub/issues/726

**Comment by kcoleman-marklogic** [comment]
Yes, I would say that's likely to be the same problem. I'll figure out how to pull 2.0.4 and try it. Thanks, Kasey.

**Comment by kcoleman-marklogic** [comment]
Kasey is correct: This is working OK with 2.0.4. Closing.
